// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: article_service.proto

package articlesapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty for now, rather than google.protobuf.Empty, so fields can be added
// without changing the method signature.
type GetArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesRequest) Reset() {
	*x = GetArticlesRequest{}
	mi := &file_article_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesRequest) ProtoMessage() {}

func (x *GetArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesRequest.ProtoReflect.Descriptor instead.
func (*GetArticlesRequest) Descriptor() ([]byte, []int) {
	return file_article_service_proto_rawDescGZIP(), []int{0}
}

type GetArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesResponse) Reset() {
	*x = GetArticlesResponse{}
	mi := &file_article_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesResponse) ProtoMessage() {}

func (x *GetArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesResponse.ProtoReflect.Descriptor instead.
func (*GetArticlesResponse) Descriptor() ([]byte, []int) {
	return file_article_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type GetArticleDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleDetailsRequest) Reset() {
	*x = GetArticleDetailsRequest{}
	mi := &file_article_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleDetailsRequest) ProtoMessage() {}

func (x *GetArticleDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetArticleDetailsRequest) Descriptor() ([]byte, []int) {
	return file_article_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetArticleDetailsRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type GetArticleDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *ArticleDetails        `protobuf:"bytes,1,opt,name=article" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleDetailsResponse) Reset() {
	*x = GetArticleDetailsResponse{}
	mi := &file_article_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleDetailsResponse) ProtoMessage() {}

func (x *GetArticleDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetArticleDetailsResponse) Descriptor() ([]byte, []int) {
	return file_article_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleDetailsResponse) GetArticle() *ArticleDetails {
	if x != nil {
		return x.Article
	}
	return nil
}

type RequestArticleStatusChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Action        *ArticleStatusAction   `protobuf:"varint,2,opt,name=action,enum=sliide.services.articles.api.ArticleStatusAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestArticleStatusChangeRequest) Reset() {
	*x = RequestArticleStatusChangeRequest{}
	mi := &file_article_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestArticleStatusChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestArticleStatusChangeRequest) ProtoMessage() {}

func (x *RequestArticleStatusChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestArticleStatusChangeRequest.ProtoReflect.Descriptor instead.
func (*RequestArticleStatusChangeRequest) Descriptor() ([]byte, []int) {
	return file_article_service_proto_rawDescGZIP(), []int{4}
}

func (x *RequestArticleStatusChangeRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RequestArticleStatusChangeRequest) GetAction() ArticleStatusAction {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ArticleStatusAction_ARTICLE_STATUS_ACTION_UNSPECIFIED
}

type RequestArticleStatusChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusChange  *StatusChange          `protobuf:"bytes,1,opt,name=status_change,json=statusChange" json:"status_change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestArticleStatusChangeResponse) Reset() {
	*x = RequestArticleStatusChangeResponse{}
	mi := &file_article_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestArticleStatusChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestArticleStatusChangeResponse) ProtoMessage() {}

func (x *RequestArticleStatusChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestArticleStatusChangeResponse.ProtoReflect.Descriptor instead.
func (*RequestArticleStatusChangeResponse) Descriptor() ([]byte, []int) {
	return file_article_service_proto_rawDescGZIP(), []int{5}
}

func (x *RequestArticleStatusChangeResponse) GetStatusChange() *StatusChange {
	if x != nil {
		return x.StatusChange
	}
	return nil
}

var File_article_service_proto protoreflect.FileDescriptor

const file_article_service_proto_rawDesc = "" +
	"\n" +
	"\x15article_service.proto\x12\x1csliide.services.articles.api\x1a\rarticle.proto\"\x14\n" +
	"\x12GetArticlesRequest\"X\n" +
	"\x13GetArticlesResponse\x12A\n" +
	"\barticles\x18\x01 \x03(\v2%.sliide.services.articles.api.ArticleR\barticles\"*\n" +
	"\x18GetArticleDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"c\n" +
	"\x19GetArticleDetailsResponse\x12F\n" +
	"\aarticle\x18\x01 \x01(\v2,.sliide.services.articles.api.ArticleDetailsR\aarticle\"~\n" +
	"!RequestArticleStatusChangeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12I\n" +
	"\x06action\x18\x02 \x01(\x0e21.sliide.services.articles.api.ArticleStatusActionR\x06action\"u\n" +
	"\"RequestArticleStatusChangeResponse\x12O\n" +
	"\rstatus_change\x18\x01 \x01(\v2*.sliide.services.articles.api.StatusChangeR\fstatusChange2\xa9\x03\n" +
	"\n" +
	"ArticleAPI\x12r\n" +
	"\vGetArticles\x120.sliide.services.articles.api.GetArticlesRequest\x1a1.sliide.services.articles.api.GetArticlesResponse\x12\x84\x01\n" +
	"\x11GetArticleDetails\x126.sliide.services.articles.api.GetArticleDetailsRequest\x1a7.sliide.services.articles.api.GetArticleDetailsResponse\x12\x9f\x01\n" +
	"\x1aRequestArticleStatusChange\x12?.sliide.services.articles.api.RequestArticleStatusChangeRequest\x1a@.sliide.services.articles.api.RequestArticleStatusChangeResponseBAZ?github.com/sliide/articles-backend/pkg/articles/api;articlesapib\beditionsp\xe8\a"

var (
	file_article_service_proto_rawDescOnce sync.Once
	file_article_service_proto_rawDescData []byte
)

func file_article_service_proto_rawDescGZIP() []byte {
	file_article_service_proto_rawDescOnce.Do(func() {
		file_article_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_article_service_proto_rawDesc), len(file_article_service_proto_rawDesc)))
	})
	return file_article_service_proto_rawDescData
}

var file_article_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_article_service_proto_goTypes = []any{
	(*GetArticlesRequest)(nil),                 // 0: sliide.services.articles.api.GetArticlesRequest
	(*GetArticlesResponse)(nil),                // 1: sliide.services.articles.api.GetArticlesResponse
	(*GetArticleDetailsRequest)(nil),           // 2: sliide.services.articles.api.GetArticleDetailsRequest
	(*GetArticleDetailsResponse)(nil),          // 3: sliide.services.articles.api.GetArticleDetailsResponse
	(*RequestArticleStatusChangeRequest)(nil),  // 4: sliide.services.articles.api.RequestArticleStatusChangeRequest
	(*RequestArticleStatusChangeResponse)(nil), // 5: sliide.services.articles.api.RequestArticleStatusChangeResponse
	(*Article)(nil),                            // 6: sliide.services.articles.api.Article
	(*ArticleDetails)(nil),                     // 7: sliide.services.articles.api.ArticleDetails
	(ArticleStatusAction)(0),                   // 8: sliide.services.articles.api.ArticleStatusAction
	(*StatusChange)(nil),                       // 9: sliide.services.articles.api.StatusChange
}
var file_article_service_proto_depIdxs = []int32{
	6, // 0: sliide.services.articles.api.GetArticlesResponse.articles:type_name -> sliide.services.articles.api.Article
	7, // 1: sliide.services.articles.api.GetArticleDetailsResponse.article:type_name -> sliide.services.articles.api.ArticleDetails
	8, // 2: sliide.services.articles.api.RequestArticleStatusChangeRequest.action:type_name -> sliide.services.articles.api.ArticleStatusAction
	9, // 3: sliide.services.articles.api.RequestArticleStatusChangeResponse.status_change:type_name -> sliide.services.articles.api.StatusChange
	0, // 4: sliide.services.articles.api.ArticleAPI.GetArticles:input_type -> sliide.services.articles.api.GetArticlesRequest
	2, // 5: sliide.services.articles.api.ArticleAPI.GetArticleDetails:input_type -> sliide.services.articles.api.GetArticleDetailsRequest
	4, // 6: sliide.services.articles.api.ArticleAPI.RequestArticleStatusChange:input_type -> sliide.services.articles.api.RequestArticleStatusChangeRequest
	1, // 7: sliide.services.articles.api.ArticleAPI.GetArticles:output_type -> sliide.services.articles.api.GetArticlesResponse
	3, // 8: sliide.services.articles.api.ArticleAPI.GetArticleDetails:output_type -> sliide.services.articles.api.GetArticleDetailsResponse
	5, // 9: sliide.services.articles.api.ArticleAPI.RequestArticleStatusChange:output_type -> sliide.services.articles.api.RequestArticleStatusChangeResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_article_service_proto_init() }
func file_article_service_proto_init() {
	if File_article_service_proto != nil {
		return
	}
	file_article_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_article_service_proto_rawDesc), len(file_article_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_article_service_proto_goTypes,
		DependencyIndexes: file_article_service_proto_depIdxs,
		MessageInfos:      file_article_service_proto_msgTypes,
	}.Build()
	File_article_service_proto = out.File
	file_article_service_proto_goTypes = nil
	file_article_service_proto_depIdxs = nil
}
