// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: article_service.proto

package articlesapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArticleAPI_GetArticles_FullMethodName                = "/sliide.services.articles.api.ArticleAPI/GetArticles"
	ArticleAPI_GetArticleDetails_FullMethodName          = "/sliide.services.articles.api.ArticleAPI/GetArticleDetails"
	ArticleAPI_RequestArticleStatusChange_FullMethodName = "/sliide.services.articles.api.ArticleAPI/RequestArticleStatusChange"
)

// ArticleAPIClient is the client API for ArticleAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleAPIClient interface {
	GetArticles(ctx context.Context, in *GetArticlesRequest, opts ...grpc.CallOption) (*GetArticlesResponse, error)
	GetArticleDetails(ctx context.Context, in *GetArticleDetailsRequest, opts ...grpc.CallOption) (*GetArticleDetailsResponse, error)
	// Asks for an article to be disabled or enabled. The change is applied
	// asynchronously by another service, so success means only that it was
	// accepted: watch Article.pending_change to see it land.
	//
	// Returns the pending change unchanged if the same action is already in
	// flight. Fails with FAILED_PRECONDITION if the article is already in the
	// requested state, or the opposite change is still pending.
	RequestArticleStatusChange(ctx context.Context, in *RequestArticleStatusChangeRequest, opts ...grpc.CallOption) (*RequestArticleStatusChangeResponse, error)
}

type articleAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleAPIClient(cc grpc.ClientConnInterface) ArticleAPIClient {
	return &articleAPIClient{cc}
}

func (c *articleAPIClient) GetArticles(ctx context.Context, in *GetArticlesRequest, opts ...grpc.CallOption) (*GetArticlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticlesResponse)
	err := c.cc.Invoke(ctx, ArticleAPI_GetArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleAPIClient) GetArticleDetails(ctx context.Context, in *GetArticleDetailsRequest, opts ...grpc.CallOption) (*GetArticleDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleDetailsResponse)
	err := c.cc.Invoke(ctx, ArticleAPI_GetArticleDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleAPIClient) RequestArticleStatusChange(ctx context.Context, in *RequestArticleStatusChangeRequest, opts ...grpc.CallOption) (*RequestArticleStatusChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestArticleStatusChangeResponse)
	err := c.cc.Invoke(ctx, ArticleAPI_RequestArticleStatusChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleAPIServer is the server API for ArticleAPI service.
// All implementations must embed UnimplementedArticleAPIServer
// for forward compatibility.
type ArticleAPIServer interface {
	GetArticles(context.Context, *GetArticlesRequest) (*GetArticlesResponse, error)
	GetArticleDetails(context.Context, *GetArticleDetailsRequest) (*GetArticleDetailsResponse, error)
	// Asks for an article to be disabled or enabled. The change is applied
	// asynchronously by another service, so success means only that it was
	// accepted: watch Article.pending_change to see it land.
	//
	// Returns the pending change unchanged if the same action is already in
	// flight. Fails with FAILED_PRECONDITION if the article is already in the
	// requested state, or the opposite change is still pending.
	RequestArticleStatusChange(context.Context, *RequestArticleStatusChangeRequest) (*RequestArticleStatusChangeResponse, error)
	mustEmbedUnimplementedArticleAPIServer()
}

// UnimplementedArticleAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleAPIServer struct{}

func (UnimplementedArticleAPIServer) GetArticles(context.Context, *GetArticlesRequest) (*GetArticlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArticles not implemented")
}
func (UnimplementedArticleAPIServer) GetArticleDetails(context.Context, *GetArticleDetailsRequest) (*GetArticleDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArticleDetails not implemented")
}
func (UnimplementedArticleAPIServer) RequestArticleStatusChange(context.Context, *RequestArticleStatusChangeRequest) (*RequestArticleStatusChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestArticleStatusChange not implemented")
}
func (UnimplementedArticleAPIServer) mustEmbedUnimplementedArticleAPIServer() {}
func (UnimplementedArticleAPIServer) testEmbeddedByValue()                    {}

// UnsafeArticleAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleAPIServer will
// result in compilation errors.
type UnsafeArticleAPIServer interface {
	mustEmbedUnimplementedArticleAPIServer()
}

func RegisterArticleAPIServer(s grpc.ServiceRegistrar, srv ArticleAPIServer) {
	// If the following call panics, it indicates UnimplementedArticleAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleAPI_ServiceDesc, srv)
}

func _ArticleAPI_GetArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleAPIServer).GetArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleAPI_GetArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleAPIServer).GetArticles(ctx, req.(*GetArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleAPI_GetArticleDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleAPIServer).GetArticleDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleAPI_GetArticleDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleAPIServer).GetArticleDetails(ctx, req.(*GetArticleDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleAPI_RequestArticleStatusChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestArticleStatusChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleAPIServer).RequestArticleStatusChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleAPI_RequestArticleStatusChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleAPIServer).RequestArticleStatusChange(ctx, req.(*RequestArticleStatusChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleAPI_ServiceDesc is the grpc.ServiceDesc for ArticleAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sliide.services.articles.api.ArticleAPI",
	HandlerType: (*ArticleAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticles",
			Handler:    _ArticleAPI_GetArticles_Handler,
		},
		{
			MethodName: "GetArticleDetails",
			Handler:    _ArticleAPI_GetArticleDetails_Handler,
		},
		{
			MethodName: "RequestArticleStatusChange",
			Handler:    _ArticleAPI_RequestArticleStatusChange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "article_service.proto",
}
